version: '3.9'
services:
  dev:
    build:
      context: '.'
      dockerfile: 'dev.Dockerfile'
    restart: 'always'
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
