version: '3.9'
services:
  graphdb:
    extends:
      file: docker-compose-backend.yml
      service: graphdb
  api:
    depends_on: ['graphdb']
    image: fredrbus/tk_sdg_api:1.0
    ports:
      - '3001:3001'
    environment:
      - GRAPHDB_BASE_URL=http://graphdb:7200
  web:
    depends_on: ['api', 'graphdb']
    extends:
      file: docker-compose-frontend.yml
      service: web
