version: '3.9'
services:
  graphdb:
    image: fredrbus/tk_sdg_db:0.1
    ports:
      - '7200:7200'
  api:
    depends_on: ['graphdb']
    image: fredrbus/tk_sdg_api:0.1
    ports:
      - '3001:3001'
    environment:
      - GRAPHDB_BASE_URL=http://graphdb:7200
