version: '3.9'
services:
  graphdb:
    extends:
      file: docker-compose-backend.yml
      service: graphdb
  api:
    depends_on: ['graphdb']
    extends:
      file: docker-compose-backend.yml
      service: api
    ports:
      - '3001:3001'
    environment:
      - GRAPHDB_BASE_URL=http://graphdb:7200
  web:
    depends_on: ['api', 'graphdb']
    extends:
      file: docker-compose-frontend.yml
      service: web
    command:
      ['./utils/await_login.sh', 'api', 'http-server', 'build', '-p', '80']
